services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_DB_HOST=db
      - STREAMLIT_DB_PORT=3306
      - STREAMLIT_DB_USER=root
      - STREAMLIT_DB_PASS=root
      - STREAMLIT_DB_NAME=investment_risk_bi
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=investment_risk_bi
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
