[client]
showDeployButton = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff9900"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
font = "sans serif"
